Repository DEPthes/MJU-Council-Server, pull requests merged in 2024-12, with the labels that each got.

#30 [FEAT] 행사 API 구현
  src/main/java/depth/mju/council/domain/business/controller/BusinessController.java
  src/main/java/depth/mju/council/domain/business/service/BusinessService.java
  src/main/java/depth/mju/council/domain/event/controller/EventController.java
  src/main/java/depth/mju/council/domain/event/dto/req/CreateEventDetailReq.java
  src/main/java/depth/mju/council/domain/event/dto/req/CreateEventReq.java
  src/main/java/depth/mju/council/domain/event/dto/req/ModifyEventDetailReq.java
  src/main/java/depth/mju/council/domain/event/dto/req/ModifyEventReq.java
  src/main/java/depth/mju/council/domain/event/dto/res/EventDetailListRes.java
  src/main/java/depth/mju/council/domain/event/dto/res/EventDetailRes.java
  src/main/java/depth/mju/council/domain/event/dto/res/EventListRes.java
  src/main/java/depth/mju/council/domain/event/dto/res/EventRes.java
  src/main/java/depth/mju/council/domain/event/entity/Event.java
  src/main/java/depth/mju/council/domain/event/entity/EventDetail.java
  src/main/java/depth/mju/council/domain/event/entity/EventDetailFile.java
  src/main/java/depth/mju/council/domain/event/repository/EventDetailFileRepository.java
  src/main/java/depth/mju/council/domain/event/repository/EventDetailRepository.java
  src/main/java/depth/mju/council/domain/event/repository/EventFileRepository.java
  src/main/java/depth/mju/council/domain/event/repository/EventRepository.java
  src/main/java/depth/mju/council/domain/event/service/EventService.java
  src/main/java/depth/mju/council/domain/notice/controller/NoticeController.java
  src/main/java/depth/mju/council/domain/notice/service/NoticeService.java
Labels: 🌈 기능

#31 [FEAT] 회의록 사진 로직 구현
  src/main/java/depth/mju/council/domain/minute/controller/MinuteController.java
  src/main/java/depth/mju/council/domain/minute/dto/req/ModifyMinuteReq.java
  src/main/java/depth/mju/council/domain/minute/dto/res/GetMinuteFileRes.java
  src/main/java/depth/mju/council/domain/minute/dto/res/GetMinuteRes.java
  src/main/java/depth/mju/council/domain/minute/entity/MinuteFile.java
  src/main/java/depth/mju/council/domain/minute/repository/MinuteFileRepository.java
  src/main/java/depth/mju/council/domain/minute/service/MinuteService.java
Labels: 🌈 기능

#33 [FEAT] 회칙 API 구현
  src/main/java/depth/mju/council/domain/minute/controller/MinuteController.java
  src/main/java/depth/mju/council/domain/minute/dto/res/GetMinuteRes.java
  src/main/java/depth/mju/council/domain/minute/service/MinuteService.java
  src/main/java/depth/mju/council/domain/regulation/controller/RegulationController.java
  src/main/java/depth/mju/council/domain/regulation/dto/req/CreateRegulationReq.java
  src/main/java/depth/mju/council/domain/regulation/dto/req/ModifyRegulationReq.java
  src/main/java/depth/mju/council/domain/regulation/dto/res/GetAllRegulationRes.java
  src/main/java/depth/mju/council/domain/regulation/dto/res/GetRegulationFileRes.java
  src/main/java/depth/mju/council/domain/regulation/dto/res/GetRegulationRes.java
  src/main/java/depth/mju/council/domain/regulation/entity/Regulation.java
  src/main/java/depth/mju/council/domain/regulation/entity/RegulationFile.java
  src/main/java/depth/mju/council/domain/regulation/repository/RegulationFileRepository.java
  src/main/java/depth/mju/council/domain/regulation/repository/RegulationRepository.java
  src/main/java/depth/mju/council/domain/regulation/service/RegulationService.java
  src/main/java/depth/mju/council/global/config/SecurityConfig.java
Labels: 🌈 기능

#35 [FIX] 파일 오류 수정
  src/main/java/depth/mju/council/domain/regulation/repository/RegulationRepository.java
  src/main/java/depth/mju/council/domain/regulation/service/RegulationService.java
Labels: 🛠️ 리팩토링

#34 [FEAT] 중운위(단과대) API 구현
  src/main/java/depth/mju/council/domain/committe/controller/CommitteeController.java
  src/main/java/depth/mju/council/domain/committe/dto/req/CreateCommitteeReq.java
  src/main/java/depth/mju/council/domain/committe/dto/res/CommitteeRes.java
  src/main/java/depth/mju/council/domain/committe/entity/Committee.java
  src/main/java/depth/mju/council/domain/committe/repository/CommitteeRepository.java
  src/main/java/depth/mju/council/domain/committe/service/CommitteeService.java
Labels: 🌈 기능

#36 [FEAT] 제휴 API 구현
  src/main/java/depth/mju/council/domain/alliance/controller/AllianceController.java
  src/main/java/depth/mju/council/domain/alliance/dto/req/CreateAllianceReq.java
  src/main/java/depth/mju/council/domain/alliance/dto/req/ModifyAllianceReq.java
  src/main/java/depth/mju/council/domain/alliance/dto/res/AllianceListRes.java
  src/main/java/depth/mju/council/domain/alliance/dto/res/AllianceRes.java
  src/main/java/depth/mju/council/domain/alliance/entity/Alliance.java
  src/main/java/depth/mju/council/domain/alliance/repository/AllianceFileRepository.java
  src/main/java/depth/mju/council/domain/alliance/repository/AllianceRepository.java
  src/main/java/depth/mju/council/domain/alliance/service/AllianceService.java
  src/main/java/depth/mju/council/domain/business/controller/BusinessController.java
  src/main/java/depth/mju/council/domain/business/repository/BusinessFileRepository.java
  src/main/java/depth/mju/council/domain/business/service/BusinessService.java
  src/main/java/depth/mju/council/domain/event/dto/req/ModifyEventReq.java
  src/main/java/depth/mju/council/domain/event/entity/Event.java
  src/main/java/depth/mju/council/domain/event/repository/EventDetailFileRepository.java
  src/main/java/depth/mju/council/domain/event/repository/EventDetailRepository.java
  src/main/java/depth/mju/council/domain/event/repository/EventFileRepository.java
  src/main/java/depth/mju/council/domain/event/service/EventService.java
  src/main/java/depth/mju/council/domain/notice/controller/NoticeController.java
  src/main/java/depth/mju/council/domain/notice/repository/NoticeFileRepository.java
  src/main/java/depth/mju/council/domain/notice/service/NoticeService.java
Labels: 🌈 기능, 🛠️ 리팩토링

#42 [FEAT] 배너부분 사진 저장로직 추가
  src/main/java/depth/mju/council/domain/banner/controller/BannerController.java
  src/main/java/depth/mju/council/domain/banner/service/BannerService.java
Labels: 🌈 기능

#37 [FEAT] 총학정보 API 구현
  src/main/java/depth/mju/council/domain/committe/dto/res/CommitteeRes.java
  src/main/java/depth/mju/council/domain/orgarnization/dto/res/OrganizationRes.java
  src/main/java/depth/mju/council/domain/user/controller/CouncilController.java
  src/main/java/depth/mju/council/domain/user/dto/req/UpdateCouncilReq.java
  src/main/java/depth/mju/council/domain/user/dto/res/CouncilRes.java
  src/main/java/depth/mju/council/domain/user/entity/UserEntity.java
  src/main/java/depth/mju/council/domain/user/repository/UserRepository.java
  src/main/java/depth/mju/council/domain/user/service/CouncilService.java
Labels: 🌈 기능

#45 [FIX] 삭제 로직 일괄 수정
  src/main/java/depth/mju/council/domain/alliance/repository/AllianceFileRepository.java
  src/main/java/depth/mju/council/domain/alliance/service/AllianceService.java
  src/main/java/depth/mju/council/domain/business/repository/BusinessFileRepository.java
  src/main/java/depth/mju/council/domain/business/service/BusinessService.java
  src/main/java/depth/mju/council/domain/event/repository/EventDetailFileRepository.java
  src/main/java/depth/mju/council/domain/event/repository/EventFileRepository.java
  src/main/java/depth/mju/council/domain/event/service/EventService.java
  src/main/java/depth/mju/council/domain/notice/repository/NoticeFileRepository.java
  src/main/java/depth/mju/council/domain/notice/service/NoticeService.java
Labels: 🛠️ 리팩토링

#46 [FEAT] 국별 소개 API 구현/조직도 API 및 시큐리티 설정 변경
  src/main/java/depth/mju/council/domain/department/controller/DepartmentController.java
  src/main/java/depth/mju/council/domain/department/dto/res/DepartmentRes.java
  src/main/java/depth/mju/council/domain/department/entity/Department.java
  src/main/java/depth/mju/council/domain/department/repository/DepartmentRepository.java
  src/main/java/depth/mju/council/domain/department/service/DepartmentService.java
  src/main/java/depth/mju/council/domain/orgarnization/controller/OrganizationController.java
  src/main/java/depth/mju/council/domain/orgarnization/service/OrganizationService.java
  src/main/java/depth/mju/council/global/config/SecurityConfig.java
Labels: 🌈 기능

#47 [FEAT] 소개이미지 API
  src/main/java/depth/mju/council/domain/user/controller/CouncilController.java
  src/main/java/depth/mju/council/domain/user/controller/UserImageController.java
  src/main/java/depth/mju/council/domain/user/dto/res/CouncilImageRes.java
  src/main/java/depth/mju/council/domain/user/entity/CouncilImage.java
  src/main/java/depth/mju/council/domain/user/repository/CouncilImageRepository.java
  src/main/java/depth/mju/council/domain/user/service/CouncilService.java
  src/main/java/depth/mju/council/domain/user/service/UserImageService.java
Labels: 🌈 기능

#51 [FIX] 행사 세부사항 기능 수정
  src/main/java/depth/mju/council/domain/event/controller/EventController.java
  src/main/java/depth/mju/council/domain/event/dto/req/ModifyEventDetailReq.java
  src/main/java/depth/mju/council/domain/event/dto/res/EventDetailRes.java
  src/main/java/depth/mju/council/domain/event/repository/EventDetailRepository.java
  src/main/java/depth/mju/council/domain/event/service/EventService.java
Labels: 🌈 기능

#52 [FIX] 학생회칙 requestPart 수정
  src/main/java/depth/mju/council/domain/regulation/controller/RegulationController.java
Labels: 🛠️ 리팩토링

#53 [FIX] patch -> put 수정
  src/main/java/depth/mju/council/domain/minute/controller/MinuteController.java
  src/main/java/depth/mju/council/domain/regulation/controller/RegulationController.java
Labels: 🛠️ 리팩토링
